### ISSUE TITLE
The problem of seeking data sets

### ISSUE THREAD

**Issue by AwakerLee** [kalenforn/clip-based-cross-modal-hash#1]
The downloaded dataset is ten zip files, is this the extracted features? These zip files need to be treated as such.
Notice: please run the change_index_path.py in the mat dir for each dataset, and replace the "path_replace" with the "images" dir. There is no change_index_path.py file.

**Comment by kalenforn** [comment]
We push 10 tar files into the Baidu skydisk, including coco, nuswide, and mirflickr25k datasets. The "change_index_path.py" file is in xxx/mat/ path, like PATH_TO_DOWNLOAD_DARASETS/coco/mat/change_index_path.py. The "label.mat" contains the category labels, "index_original.mat" saves the image path for each picture, "caption.mat" is the language description for each image. We utilize the original picture for training.

To make your "index.mat" file, please replace the "path_replace" with the "images" dir. The "images" dir is in the previous dir of "mat".
